# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\python打的代码\QTwindow\计算器\计算器.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import math as h

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(585, 500)
        MainWindow.setMinimumSize(QtCore.QSize(585, 500))
        MainWindow.setMaximumSize(QtCore.QSize(585, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./1.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("./1.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("./1.bmp"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(390, 371, 195, 64))
        font = QtGui.QFont()
        font.setFamily("方正舒体")
        font.setPointSize(20)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(0, 30, 585, 80))
        self.lcdNumber.setMinimumSize(QtCore.QSize(400, 75))
        self.lcdNumber.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lcdNumber.setDigitCount(16)
        self.lcdNumber.setObjectName("lcdNumber")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(234, 307, 117, 64))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(351, 115, 117, 64))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(468, 115, 117, 64))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(351, 243, 117, 64))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(351, 179, 117, 64))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(468, 179, 117, 64))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(351, 307, 117, 64))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(468, 307, 117, 64))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(468, 243, 117, 64))
        font = QtGui.QFont()
        font.setFamily("方正舒体")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_11.setGeometry(QtCore.QRect(0, 115, 117, 64))
        self.pushButton_11.setMinimumSize(QtCore.QSize(0, 55))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_12.setGeometry(QtCore.QRect(117, 115, 117, 64))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_13.setGeometry(QtCore.QRect(234, 115, 117, 64))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_14.setGeometry(QtCore.QRect(0, 179, 117, 64))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_15.setGeometry(QtCore.QRect(117, 179, 117, 64))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_16.setGeometry(QtCore.QRect(234, 179, 117, 64))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(0, 243, 117, 64))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(117, 243, 117, 64))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(234, 243, 117, 64))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(0, 307, 117, 64))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(195, 371, 195, 64))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setObjectName("pushButton_21")
        
        # datetime=QtCore.QDateTime.currentDateTime()
        date=QtCore.QDate.currentDate()
        # self.dateEdit = QtWidgets.QDateEdit(datetime)
        self.dateEdit =QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setDate(date)
        self.dateEdit.setGeometry(QtCore.QRect(0, 0, 200, 30))
        self.dateEdit.setObjectName("dateEdit")
        self.dateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateEdit.setDisplayFormat("yyyy/MM/dd")
        print(date.toString(QtCore.Qt.DefaultLocaleLongDate))
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 0, 60, 30))
        font = QtGui.QFont()
        font.setFamily("方正舒体")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(117, 307, 117, 64))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(0, 371, 195, 64))
        font = QtGui.QFont()
        font.setFamily("方正舒体")
        font.setPointSize(20)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName("pushButton_23")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(260, 0, 80, 30))
        font = QtGui.QFont()
        font.setFamily("方正舒体")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 0, 60, 30))
        font = QtGui.QFont()
        font.setFamily("方正舒体")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(400, 0, 80, 30))
        font = QtGui.QFont()
        font.setFamily("方正舒体")
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 585, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.close)
        self.pushButton_2.clicked.connect(self.Add)
        self.pushButton_3.clicked.connect(self.Sub)
        self.pushButton_4.clicked.connect(self.multiply)
        self.pushButton_5.clicked.connect(self.divis)
        self.pushButton_6.clicked.connect(self.after)
        self.pushButton_7.clicked.connect(self.cube)
        self.pushButton_8.clicked.connect(self.ping)
        self.pushButton_9.clicked.connect(self.genhao)
        self.pushButton_10.clicked.connect(self.changtoer)
        self.pushButton_11.clicked.connect(self.NumInput_1)
        self.pushButton_12.clicked.connect(self.NumInput_2)
        self.pushButton_13.clicked.connect(self.NumInput_3)
        self.pushButton_14.clicked.connect(self.NumInput_4)
        self.pushButton_15.clicked.connect(self.NumInput_5)
        self.pushButton_16.clicked.connect(self.NumInput_6)
        self.pushButton_17.clicked.connect(self.NumInput_7)
        self.pushButton_18.clicked.connect(self.NumInput_8)
        self.pushButton_19.clicked.connect(self.NumInput_9)
        self.pushButton_20.clicked.connect(self.NumInput_0)
        self.pushButton_21.clicked.connect(self.Equals)
        self.pushButton_22.clicked.connect(self.Dian)
        self.pushButton_23.clicked.connect(self.ReSet)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.dateEdit, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.pushButton_4)
        MainWindow.setTabOrder(self.pushButton_4, self.pushButton_5)
        MainWindow.setTabOrder(self.pushButton_5, self.pushButton_6)
        MainWindow.setTabOrder(self.pushButton_6, self.pushButton_7)
        MainWindow.setTabOrder(self.pushButton_7, self.pushButton_8)
        MainWindow.setTabOrder(self.pushButton_8, self.pushButton_9)
        MainWindow.setTabOrder(self.pushButton_9, self.pushButton_10)
        MainWindow.setTabOrder(self.pushButton_10, self.pushButton_11)
        MainWindow.setTabOrder(self.pushButton_11, self.pushButton_12)
        MainWindow.setTabOrder(self.pushButton_12, self.pushButton_13)
        MainWindow.setTabOrder(self.pushButton_13, self.pushButton_14)
        MainWindow.setTabOrder(self.pushButton_14, self.pushButton_15)
        MainWindow.setTabOrder(self.pushButton_15, self.pushButton_16)
        MainWindow.setTabOrder(self.pushButton_16, self.pushButton_17)
        MainWindow.setTabOrder(self.pushButton_17, self.pushButton_18)
        MainWindow.setTabOrder(self.pushButton_18, self.pushButton_19)
        MainWindow.setTabOrder(self.pushButton_19, self.pushButton_20)
        MainWindow.setTabOrder(self.pushButton_20, self.pushButton_21)
        MainWindow.setTabOrder(self.pushButton_21, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "计算器"))
        self.pushButton.setText(_translate("MainWindow", "关闭"))
        self.pushButton_2.setText(_translate("MainWindow", "+"))
        self.pushButton_3.setText(_translate("MainWindow", "-"))
        self.pushButton_4.setText(_translate("MainWindow", "*"))
        self.pushButton_5.setText(_translate("MainWindow", "/"))
        self.pushButton_6.setText(_translate("MainWindow", "%"))
        self.pushButton_7.setText(_translate("MainWindow", "x^3"))
        self.pushButton_8.setText(_translate("MainWindow", "x^2"))
        self.pushButton_9.setText(_translate("MainWindow", "x^0.5"))
        self.pushButton_10.setText(_translate("MainWindow", "二进制"))
        self.pushButton_11.setText(_translate("MainWindow", "1"))
        self.pushButton_12.setText(_translate("MainWindow", "2"))
        self.pushButton_13.setText(_translate("MainWindow", "3"))
        self.pushButton_14.setText(_translate("MainWindow", "4"))
        self.pushButton_15.setText(_translate("MainWindow", "5"))
        self.pushButton_16.setText(_translate("MainWindow", "6"))
        self.pushButton_17.setText(_translate("MainWindow", "7"))
        self.pushButton_18.setText(_translate("MainWindow", "8"))
        self.pushButton_19.setText(_translate("MainWindow", "9"))
        self.pushButton_20.setText(_translate("MainWindow", "0"))
        self.pushButton_21.setText(_translate("MainWindow", "="))
        self.label.setText(_translate("MainWindow", "班级:"))
        self.pushButton_22.setText(_translate("MainWindow", "."))
        self.pushButton_23.setText(_translate("MainWindow", "清空"))
        self.lineEdit.setText(_translate("MainWindow", "信卓12001"))
        self.label_2.setText(_translate("MainWindow", "姓名:"))
        self.lineEdit_2.setText(_translate("MainWindow", "金魔人"))
        
    def __init__(self): 
        # global isdian
        self.isdian =False
        self.num1=0
        self.num=0
        self.temp=''            #获取数字
        self.sum=0              #获取和
        self.operation=[]       #得到运算符号的排列
        self.numbers=[]         #得到数字的输入顺序
    
    def NumInput_1(self): 
        self.temp+='1'
        if self.isdian:
            self.num=float(self.temp)
        else: 
            self.num=int(self.temp)
        self.lcdNumber.setProperty("value",self.num)
        
    def NumInput_2(self): 
        self.temp+='2'
        if self.isdian:
            self.num=float(self.temp)
        else: 
            self.num=int(self.temp)
        self.lcdNumber.setProperty("value",self.num)
        
    def NumInput_3(self): 
        self.temp+='3'
        if self.isdian:
            self.num=float(self.temp)
        else: 
            self.num=int(self.temp)
        self.lcdNumber.setProperty("value",self.num)
    
    def NumInput_4(self): 
        self.temp+='4'
        if self.isdian:
            self.num=float(self.temp)
        else: 
            self.num=int(self.temp)
        self.lcdNumber.setProperty("value",self.num)
        
    def NumInput_5(self): 
        self.temp+='5'
        if self.isdian:
            self.num=float(self.temp)
        else: 
            self.num=int(self.temp)
        self.lcdNumber.setProperty("value",self.num)
        
    def NumInput_6(self): 
        self.temp+='6'
        if self.isdian:
            self.num=float(self.temp)
        else: 
            self.num=int(self.temp)
        self.lcdNumber.setProperty("value",self.num)
        
    def NumInput_7(self): 
        self.temp+='7'
        if self.isdian:
            self.num=float(self.temp)
        else: 
            self.num=int(self.temp)
        self.lcdNumber.setProperty("value",self.num)
        
    def NumInput_8(self): 
        self.temp+='8'
        if self.isdian:
            self.num=float(self.temp)
        else: 
            self.num=int(self.temp)
        self.lcdNumber.setProperty("value",self.num)
        
    def NumInput_9(self): 
        self.temp+='9'
        if self.isdian:
            self.num=float(self.temp)
        else: 
            self.num=int(self.temp)
        self.lcdNumber.setProperty("value",self.num)
        
    def NumInput_0(self): 
        self.temp+='0'
        if self.isdian:
            self.num=float(self.temp)
        else: 
            self.num=int(self.temp)
        self.lcdNumber.setProperty("value",self.num)
        
    def Add(self):
        self.numbers.append(self.num)
        self.operation.append('+')
        self.temp=''
        
    def Sub(self):
        self.numbers.append(self.num)
        self.operation.append('-')
        self.temp=''
    
    def multiply(self):
        self.numbers.append(self.num)
        self.operation.append('*')
        self.temp=''
        
    def divis(self):
        self.numbers.append(self.num)
        self.operation.append('/')
        self.temp=''
        
    def after(self):
        self.numbers.append(self.num)
        self.operation.append('%')
        self.temp=''
        
    def cube(self):
        if self.sum==0:
            self.sum=self.num
        self.sum=h.pow(float(self.sum),3)
        self.lcdNumber.setProperty("value",self.sum)
        
    def ping(self):
        if self.sum==0:
            self.sum=self.num
        self.sum=h.pow(float(self.sum),2)
        self.lcdNumber.setProperty("value",self.sum)
        
    def genhao(self):
        if self.sum==0:
            self.sum=self.num
        self.sum=h.sqrt(float(self.sum))
        self.lcdNumber.setProperty("value",self.sum)
        
    def changtoer(self):
        if self.sum==0:
            self.sum=self.num
        a=0
        i=0
        b=self.sum
        while i<16:
            a=a+int(b%2)*int(h.pow(10,i))
            i=i+1
            b=b/2
        self.sum=a
        self.lcdNumber.setProperty("value",self.sum)
        
    def ReSet(self):        #重置计算器
        self.sum=0
        self.temp=''
        self.num1=0
        self.numbers=[]
        self.operation=[]
        self.lcdNumber.setProperty("value",self.sum)
        
    def Equals(self):       #输出结果
        self.numbers.append(self.num)
        if len(self.numbers)>0:
                self.num1=self.numbers[0]
        for i in range(len(self.numbers)):
            if i+1<len(self.numbers):
                if self.operation[i]=='*':
                    self.num1*=self.numbers[i+1]
                elif self.operation[i]=='+':
                    self.num1+=self.numbers[i+1]
                elif self.operation[i]=='-':
                    self.num1-=self.numbers[i+1]
                elif self.operation[i]=='/':
                    self.num1/=self.numbers[i+1]
                elif self.operation[i]=='%':
                    self.num1=self.num1%self.numbers[i+1]
        self.sum=self.num1
        self.lcdNumber.setProperty("value",self.sum)
                    
    def Dian(self):
        self.temp+='.'
        self.isdian=True        
# import image_rc

import sys
# 主方法，程序从此处启动PyQt设计的窗体
if __name__ == '__main__':
   app = QtWidgets.QApplication(sys.argv)
   app.setStyle("Fusion") # 设置窗口风格
   MainWindow = QtWidgets.QMainWindow() # 创建窗体对象
   ui = Ui_MainWindow() # 创建PyQt设计的窗体对象
   MainWindow.setWindowFlags(QtCore.Qt.WindowCloseButtonHint)
   ui.setupUi(MainWindow) # 调用PyQt窗体的方法对窗体对象进行初始化设置
   MainWindow.show() # 显示窗体
   sys.exit(app.exec_()) # 程序关闭时退出进程
